### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#109]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by matthewmorgan** [comment]
This track is missing a few of the above mentioned tests.  It does have a test that puts alphabetic characters at the beginning AND end of the input (in the same single test).  To make it complete we should add:

* alphabetic characters at the beginning of a valid binary number
* alphabetic characters at the end of a valid binary number
* alphabetic characters in the middle of an otherwise valid binary number

**Comment by kytrinyx** [comment]
Yeah, you could probably split the existing test into two tests (I think if you have one for the beginning and one for the end, a test for both beginning and end is redundant).

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, due to https://github.com/exercism/x-common/issues/279
