### ISSUE TITLE
queen-attack solution expects two files

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#185]
The `queen-attack` implementation I wrote involves users writing non-trivial code in [two separate files](https://github.com/exercism/xjava/tree/eea1d43a85df58316179b5ba5860e7b516c56452/exercises/queen-attack/src/example/java): `BoardCoordinate.java` and `QueenAttackCalculator.java`. At the time, I did not realize that users are [currently only able to submit a single file as a solution to a problem](http://cli.exercism.io/):

> You only need to submit the code you wrote to solve the exercise, not the test suite that you were given. At the moment each exercise must be solved in a single file.

Will this present a problem when users attempt to solve this problem?

**Comment by stkent** [comment]
To check what happens, I submitted the example solution's `QueenAttackCalculator.java` using the CLI client. It uploaded to the website fine - are tests not run against submissions? I was expecting them to fail due to the `BoardCoordinate` class not being available at compile time.

**Comment by NobbZ** [comment]
You can send as many files as you want per the CLI as long as they can be mapped to the same problem. I've did this several times through various tracks with altered tests or some benchmarking results, as well as I did it on purpose with C and C++ tracks. AFAIK sending multiple files is possible since V2.0. Perhaps that page needs to be changed.

Also it was never intended that submitted code will be tested. In general exercism assumes you do submit only tested code, also we have the request-help feature, which allows you to send unfinished code (which would not pass the tests) to the page and then hit the "request for help" button on the submitted exercise page.

**Comment by stkent** [comment]
Thanks for the info; that all makes sense! I'll look into updating the copy on the CLI info page :)

**Comment by stkent** [comment]
Closing this; should be addressed by the linked issue ^
