### ISSUE TITLE
anagram: Fix assertEquals()'s param order in test testIdenticalWordIsNotAnagram()

### ISSUE THREAD

**Issue by ZacharyRSmith** [exercism/xjava#228]
This is what we have:

![screen shot 2016-12-26 at 11 20 19 am](https://cloud.githubusercontent.com/assets/7988520/21484236/51f841ae-cb5d-11e6-852d-2cbc8fb05dd1.png)

Which produces confusing AssertionErrors because `assertEquals()`'s params are passed in the wrong order:

![screen shot 2016-12-26 at 11 20 48 am](https://cloud.githubusercontent.com/assets/7988520/21484252/82eebe64-cb5d-11e6-8b77-ab0f5aa1d34e.png)

**Comment by jtigger** [comment]
First off, @ZacharyRSmith, we really appreciate you calling this out! 

When we sat back and thought about it, the output from the test suite is the most important aspect of the user experience of Exercism.  Since then, we've been intolerant to outright defects and really nitpicky about keeping the signal-to-noise ratio as high as possible.

Your pointing out what might seem like a little thing is actually a great help to something we deeply care about.  Thanks! 🏆

...

The even better news is that @sit fixed this specific defect in 3fdc2d1b9c8749bee26140c359d93fc3a2681889 and @FridaTveit adjusted it to use the included Hamcrest matchers in 8c00848b13cc3c828798cf4c16e464f9c7c7297a.

That first commit was from almost exactly a year ago.  Not sure how that is coming down through a recent fetch.  I checked it myself and got @FridaTveit's version of it.

Bottom-line: if you see things like this, please continue to report them!
