### ISSUE TITLE
queen-attack: reorder tests

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#234]
The tests for this exercise are currently ordered as follows:

- exceptional cases
- happy path

I think it would be more fun and consistent with other exercises to reverse this:

- happy path
- exceptional cases

Thoughts?

**Comment by jtigger** [comment]
I think it's legit to prepend the digest of this conversation with a distilled "user story" — something that is clear and actionable... throw an `<hr>` under that and keep the original question so that the comment stream makes sense.

This way, we have both the original notion *and* something that someone can work on without *having to* read the whole ticket to know what to do.

... or we can close this as a question and create a new "enhancement" issue just for the work, referencing the question issue...

Thoughts?

**Comment by stkent** [comment]
I like close and reopen with a link back to this; will implement!

**Comment by stkent** [comment]
Done; see #241.

**Comment by jtigger** [comment]
And now that I see it, me too.  Thanks, @stkent !
