### ISSUE TITLE
sieve: remove redundant array creation

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#343]
In the first test in SieveTest `Arrays.asList(new Integer[]{2})` can be changed to `Collections.singletonList(2)`. This removes the redundant array creation and is more readable.

**Comment by vasouv** [comment]
i'd like to be assigned to this one as well.

**Comment by FridaTveit** [comment]
Feel free to start working on it :)

**Comment by jtigger** [comment]
@vasouv: @FridaTveit is right in saying that since we don't have that much work in flight, right now, we'll pretty easily detect when two people are tackling the same bit of work... at this moment, you don't have to take any additional action to claim this work.

If you want that added peace-of-mind, feel free to create an empty PR with in the format: "sieve: remove redundant array creation [WIP]".  This is the clearest signal I know contributors can make to ensure others are aware there is work in progress.

**Comment by FridaTveit** [comment]
Fixed in PR #402 :)
