### ISSUE TITLE
etl: adjust API to use an instance method over class methods

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#370]
As per #177, adjust the test suite to require a solution that uses an instance method instead of a class method.

_(see #344 as an example and the conversation about Function Object vs. Value Object)_

**Comment by stkent** [comment]
@jtigger ETL already appears to [use instance methods](https://github.com/exercism/xjava/blob/2110550ec9a02e1070a31ce0a56f2f82d34c6ec3/exercises/etl/src/test/java/EtlTest.java) rather than static methods, and has done for [quite some time](https://github.com/exercism/xjava/commits/master/exercises/etl/src/test/java/EtlTest.java). Was there perhaps some other exercise you were thinking of here?

**Comment by jtigger** [comment]
medical marijuana? 🌱 

Sorry to have created work for ya, @stkent. 😬

**Comment by stkent** [comment]
Haha, no worries, I like instant-close issues!
