### ISSUE TITLE
Under what conditions test classes be "final"?

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#373]
A number of exercises (as of March 2017 there are 15) include test suites where the test class itself is `final`.

```java
public final class QueenAttackCalculatorTest {
  ...
 }
```

Test suites are the code that we deliver to practitioners and should be exemplary.  While a minor point, it can be confusing for those new-to-the-language if we use a keyword sometimes but not others.  Better to do this deliberately and consistently.

Question (@exercism/java): when should test classes be `final`?  Always?  Never?

**Comment by stkent** [comment]
I'm a `final` user (and probably abuser), so my vote is to always include. Safety first; once you get comfortable with the concept, then you know when it's safe to relax a bit. Most of my test cases also use `final` in individual test methods, but I can see there being a good case for reducing noise there.

**Comment by FridaTveit** [comment]
I wouldn't use `final` in this case. As @jtigger said, it can be confusing to people who are new to Java. I think it's better to introduce it in a situation where it's more useful and where it's more clear why it's used, e.g. a final variable. Java has a lot of syntax, that was what I found the most confusing when I started learning it, so I think minimising syntax where we can (while still maintaining good code) is a good thing. I don't feel very strongly about it though, so I'm open to being convinced otherwise :)

**Comment by matthewmorgan** [comment]
Semantically, it seems like `final` is meant to draw a line in the sand.  While I can't imagine extending and overriding this test, and I don't think I would like to work with a production test suite that does extend and override test classes (other than maybe a generic library class), I don't think it has much value in the absence of explanation.

My vote is keep, with an explanation, or drop, `final`.

**Comment by jtigger** [comment]
So... @exercism/java: which will we go with?

1. explain it
  - when would we introduce it? on the first exercise?  a little farther down?
1. drop it

**Comment by stkent** [comment]
I vote for drop.

**Comment by FridaTveit** [comment]
I vote for drop too

**Comment by stkent** [comment]
Opened an actionable issue based on this discussion; closing!
