### ISSUE TITLE
sublist: more general tests needed?

### ISSUE THREAD

**Issue by rstockbridge** [exercism/xjava#528]
[My solution to this exercise](http://exercism.io/submissions/21ba0a18f4b04698b0177e9ba89cc69f) could fail for deliberately constructed types not currently represented by the test suite (see link for more details). Would it be possible/desirable to write an xjava specific test case to force implementers to address this?

**Comment by stkent** [comment]
I thought about this some more, and my conclusion was that it is _not_ desirable to write a test to cover this case. The additional complexity introduced in the starter source would likely confuse, rather than enlighten, implementers. I'd also consider any `toString` implementation that didn't differentiate between differently-valued instances to itself be broken. Interesting edge case, though!
