### ISSUE TITLE
Change design of meetup problem

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#9]
@pminten brought up a very good point about the API of meetup being
pretty terrible (See exercism/exercism.io#950).

If the meetup problem has not already been fixed in this track, we should
improve the test suite and example code to give the API a better design.

**Comment by winterchord** [comment]
It looks like the meetup problem already matches proposed API and from https://github.com/exercism/exercism.io/pull/953. See the java [test](https://github.com/exercism/xjava/blob/6753d9cc3e4518eb2afefcd64e264a9839701aee/meetup/src/test/java/MeetupTest.java#L16). The problem also has a straight-forward solution.

I think it makes sense to close this issue.

I do wonder if it makes to switch the problem's implementation away from joda-time and to JSR310 since we're requiring java 8 as the minimum version. But that's a separate topic.

**Comment by matthewmorgan** [comment]
Closed, but referenced in #116.
